// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddDomainReq struct {
	Domain string `json:"domain"`
}

type AddDomainResp struct {
	Id int64 `json:"id"`
}

type CommonResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type CreateSnatchTaskReq struct {
	DomainId        int64  `json:"domainId"`
	Domain          string `json:"domain"`
	Priority        int64  `json:"priority,default=0"`
	TargetRegistrar string `json:"targetRegistrar,optional"`
	AutoRegister    int64  `json:"autoRegister,default=0"`
}

type CreateSnatchTaskResp struct {
	Id int64 `json:"id"`
}

type DashboardStatsResp struct {
	TotalDomains   int64 `json:"totalDomains"`
	MonitorCount   int64 `json:"monitorCount"`
	ExpiringSoon   int64 `json:"expiringSoon"`
	AvailableCount int64 `json:"availableCount"`
	SnatchPending  int64 `json:"snatchPending"`
	SnatchSuccess  int64 `json:"snatchSuccess"`
}

type DeleteDomainReq struct {
	Id int64 `path:"id"`
}

type DeleteSnatchTaskReq struct {
	Id int64 `path:"id"`
}

type ExecuteSnatchReq struct {
	Domain string `json:"domain,optional"`
	TaskId int64  `json:"taskId,optional"`
}

type ExecuteSnatchResp struct {
	Msg string `json:"msg"`
}

type DomainCheckReq struct {
	Ids []int64 `json:"ids"`
}

type DomainCheckResp struct {
	Count int64        `json:"count"`
	List  []DomainItem `json:"list,optional"`
}

type DomainItem struct {
	Id              int64                `json:"id"`
	Domain          string               `json:"domain"`
	Status          string               `json:"status"`
	ExpiryDate      string               `json:"expiryDate"`
	CreationDate    string               `json:"creationDate"`
	DeleteDate      string               `json:"deleteDate"`
	Registrar       string               `json:"registrar"`
	WhoisStatus     string               `json:"whoisStatus"`
	Monitor         int64                `json:"monitor"`
	LastChecked     string               `json:"lastChecked"`
	CreatedAt       string               `json:"createdAt"`
	LifecycleStages *LifecycleStagesItem `json:"lifecycleStages,optional"`
}

type DomainListReq struct {
	Page        int64  `form:"page,default=1"`
	PageSize    int64  `form:"pageSize,default=20"`
	Status      string `form:"status,optional"`
	Keyword     string `form:"keyword,optional"`
	Monitor     int64  `form:"monitor,optional,default=-1"`
	ExpiryStart string `form:"expiryStart,optional"`
	ExpiryEnd   string `form:"expiryEnd,optional"`
	SortField   string `form:"sortField,optional,default=expiry_date"`
	SortOrder   string `form:"sortOrder,optional,default=asc"`
}

type DomainListResp struct {
	Total int64        `json:"total"`
	List  []DomainItem `json:"list"`
}

type ImportDomainResp struct {
	Total   int64 `json:"total"`
	Success int64 `json:"success"`
	Failed  int64 `json:"failed"`
}

type LifecycleStagesItem struct {
	ExpiryDate         string `json:"expiryDate"`
	GracePeriodEnd     string `json:"gracePeriodEnd,optional"`
	RedemptionStart    string `json:"redemptionStart,optional"`
	RedemptionEnd      string `json:"redemptionEnd,optional"`
	PendingDeleteStart string `json:"pendingDeleteStart,optional"`
	PendingDeleteEnd   string `json:"pendingDeleteEnd,optional"`
	AvailableDate      string `json:"availableDate,optional"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}

type NotifySettingsResp struct {
	Id         int64  `json:"id"`
	WebhookUrl string `json:"webhookUrl"`
	ExpireDays int64  `json:"expireDays"`
	Enabled    int64  `json:"enabled"`
}

type SnatchTaskItem struct {
	Id              int64  `json:"id"`
	DomainId        int64  `json:"domainId"`
	Domain          string `json:"domain"`
	Status          string `json:"status"`
	Priority        int64  `json:"priority"`
	TargetRegistrar string `json:"targetRegistrar"`
	AutoRegister    int64  `json:"autoRegister"`
	RetryCount      int64  `json:"retryCount"`
	LastError       string `json:"lastError"`
	Result          string `json:"result"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
}

type SnatchTaskListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Status   string `form:"status,optional"`
}

type SnatchTaskListResp struct {
	Total int64            `json:"total"`
	List  []SnatchTaskItem `json:"list"`
}

type ToggleMonitorReq struct {
	Id      int64 `path:"id"`
	Monitor int64 `json:"monitor"`
}

type UpdateNotifySettingsReq struct {
	WebhookUrl string `json:"webhookUrl"`
	ExpireDays int64  `json:"expireDays"`
	Enabled    int64  `json:"enabled"`
}

type UpdateSnatchTaskReq struct {
	Id     int64  `path:"id"`
	Status string `json:"status"`
	Result string `json:"result,optional"`
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

type WhoisQueryReq struct {
	Domain string `json:"domain"`
}

type WhoisQueryResp struct {
	Domain       string `json:"domain"`
	Status       string `json:"status"`
	ExpiryDate   string `json:"expiryDate"`
	CreationDate string `json:"creationDate"`
	DeleteDate   string `json:"deleteDate"`
	Registrar    string `json:"registrar"`
	WhoisStatus  string `json:"whoisStatus"`
	CanRegister  bool   `json:"canRegister"`
	WhoisRaw     string `json:"whoisRaw"`
}
