// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	domainsFieldNames          = builder.RawFieldNames(&Domains{})
	domainsRows                = strings.Join(domainsFieldNames, ",")
	domainsRowsExpectAutoSet   = strings.Join(stringx.Remove(domainsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	domainsRowsWithPlaceHolder = strings.Join(stringx.Remove(domainsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	domainsModel interface {
		Insert(ctx context.Context, data *Domains) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Domains, error)
		FindOneByDomain(ctx context.Context, domain string) (*Domains, error)
		Update(ctx context.Context, data *Domains) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultDomainsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Domains struct {
		Id           uint64         `db:"id"`
		Domain       string         `db:"domain"`
		Status       string         `db:"status"` // registered/expired/grace_period/redemption/pending_delete/available/restricted/unknown
		ExpiryDate   sql.NullTime   `db:"expiry_date"`
		CreationDate sql.NullTime   `db:"creation_date"`
		DeleteDate   sql.NullTime   `db:"delete_date"`   // 预计删除日期
		Registrar    string         `db:"registrar"`
		WhoisRaw     sql.NullString `db:"whois_raw"`
		WhoisStatus  string         `db:"whois_status"`  // WHOIS Domain Status 原始值
		Monitor      int64          `db:"monitor"`       // 是否监控 0-否 1-是
		LastChecked  sql.NullTime   `db:"last_checked"`
		CreatedAt    time.Time      `db:"created_at"`
		UpdatedAt    time.Time      `db:"updated_at"`
	}
)

func newDomainsModel(conn sqlx.SqlConn) *defaultDomainsModel {
	return &defaultDomainsModel{
		conn:  conn,
		table: "`domains`",
	}
}

func (m *defaultDomainsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDomainsModel) FindOne(ctx context.Context, id uint64) (*Domains, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", domainsRows, m.table)
	var resp Domains
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDomainsModel) FindOneByDomain(ctx context.Context, domain string) (*Domains, error) {
	var resp Domains
	query := fmt.Sprintf("select %s from %s where `domain` = ? limit 1", domainsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, domain)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDomainsModel) Insert(ctx context.Context, data *Domains) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, domainsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Domain, data.Status, data.ExpiryDate, data.CreationDate, data.DeleteDate, data.Registrar, data.WhoisRaw, data.WhoisStatus, data.Monitor, data.LastChecked)
	return ret, err
}

func (m *defaultDomainsModel) Update(ctx context.Context, newData *Domains) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, domainsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Domain, newData.Status, newData.ExpiryDate, newData.CreationDate, newData.DeleteDate, newData.Registrar, newData.WhoisRaw, newData.WhoisStatus, newData.Monitor, newData.LastChecked, newData.Id)
	return err
}

func (m *defaultDomainsModel) tableName() string {
	return m.table
}
