// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	notifySettingsFieldNames          = builder.RawFieldNames(&NotifySettings{})
	notifySettingsRows                = strings.Join(notifySettingsFieldNames, ",")
	notifySettingsRowsExpectAutoSet   = strings.Join(stringx.Remove(notifySettingsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	notifySettingsRowsWithPlaceHolder = strings.Join(stringx.Remove(notifySettingsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	notifySettingsModel interface {
		Insert(ctx context.Context, data *NotifySettings) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*NotifySettings, error)
		Update(ctx context.Context, data *NotifySettings) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultNotifySettingsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	NotifySettings struct {
		Id         uint64    `db:"id"`
		WebhookUrl string    `db:"webhook_url"`
		ExpireDays int64     `db:"expire_days"` // 提前N天提醒
		Enabled    int64     `db:"enabled"`
		CreatedAt  time.Time `db:"created_at"`
		UpdatedAt  time.Time `db:"updated_at"`
	}
)

func newNotifySettingsModel(conn sqlx.SqlConn) *defaultNotifySettingsModel {
	return &defaultNotifySettingsModel{
		conn:  conn,
		table: "`notify_settings`",
	}
}

func (m *defaultNotifySettingsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultNotifySettingsModel) FindOne(ctx context.Context, id uint64) (*NotifySettings, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", notifySettingsRows, m.table)
	var resp NotifySettings
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotifySettingsModel) Insert(ctx context.Context, data *NotifySettings) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, notifySettingsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WebhookUrl, data.ExpireDays, data.Enabled)
	return ret, err
}

func (m *defaultNotifySettingsModel) Update(ctx context.Context, data *NotifySettings) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, notifySettingsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.WebhookUrl, data.ExpireDays, data.Enabled, data.Id)
	return err
}

func (m *defaultNotifySettingsModel) tableName() string {
	return m.table
}
