// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	notifyLogsFieldNames          = builder.RawFieldNames(&NotifyLogs{})
	notifyLogsRows                = strings.Join(notifyLogsFieldNames, ",")
	notifyLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(notifyLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	notifyLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(notifyLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	notifyLogsModel interface {
		Insert(ctx context.Context, data *NotifyLogs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*NotifyLogs, error)
		Update(ctx context.Context, data *NotifyLogs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultNotifyLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	NotifyLogs struct {
		Id         uint64         `db:"id"`
		DomainId   uint64         `db:"domain_id"`
		Domain     string         `db:"domain"`
		NotifyType string         `db:"notify_type"` // expire_warning/available/snatch_result
		Channel    string         `db:"channel"`
		Content    sql.NullString `db:"content"`
		Status     string         `db:"status"` // sent/failed
		CreatedAt  time.Time      `db:"created_at"`
	}
)

func newNotifyLogsModel(conn sqlx.SqlConn) *defaultNotifyLogsModel {
	return &defaultNotifyLogsModel{
		conn:  conn,
		table: "`notify_logs`",
	}
}

func (m *defaultNotifyLogsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultNotifyLogsModel) FindOne(ctx context.Context, id uint64) (*NotifyLogs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", notifyLogsRows, m.table)
	var resp NotifyLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotifyLogsModel) Insert(ctx context.Context, data *NotifyLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, notifyLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DomainId, data.Domain, data.NotifyType, data.Channel, data.Content, data.Status)
	return ret, err
}

func (m *defaultNotifyLogsModel) Update(ctx context.Context, data *NotifyLogs) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, notifyLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DomainId, data.Domain, data.NotifyType, data.Channel, data.Content, data.Status, data.Id)
	return err
}

func (m *defaultNotifyLogsModel) tableName() string {
	return m.table
}
