// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	snatchTasksFieldNames          = builder.RawFieldNames(&SnatchTasks{})
	snatchTasksRows                = strings.Join(snatchTasksFieldNames, ",")
	snatchTasksRowsExpectAutoSet   = strings.Join(stringx.Remove(snatchTasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	snatchTasksRowsWithPlaceHolder = strings.Join(stringx.Remove(snatchTasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	snatchTasksModel interface {
		Insert(ctx context.Context, data *SnatchTasks) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SnatchTasks, error)
		Update(ctx context.Context, data *SnatchTasks) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSnatchTasksModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SnatchTasks struct {
		Id              uint64         `db:"id"`
		DomainId        uint64         `db:"domain_id"`
		Domain          string         `db:"domain"`
		Status          string         `db:"status"`         // pending/processing/success/failed
		Priority        int64          `db:"priority"`       // 优先级，越大越高
		TargetRegistrar string         `db:"target_registrar"`
		AutoRegister    int64          `db:"auto_register"`  // 是否自动注册 0-否 1-是
		RetryCount      int64          `db:"retry_count"`    // 重试次数
		LastError       sql.NullString `db:"last_error"`     // 最后一次错误信息
		Result          sql.NullString `db:"result"`
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
	}
)

func newSnatchTasksModel(conn sqlx.SqlConn) *defaultSnatchTasksModel {
	return &defaultSnatchTasksModel{
		conn:  conn,
		table: "`snatch_tasks`",
	}
}

func (m *defaultSnatchTasksModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSnatchTasksModel) FindOne(ctx context.Context, id uint64) (*SnatchTasks, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", snatchTasksRows, m.table)
	var resp SnatchTasks
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSnatchTasksModel) Insert(ctx context.Context, data *SnatchTasks) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, snatchTasksRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DomainId, data.Domain, data.Status, data.Priority, data.TargetRegistrar, data.AutoRegister, data.RetryCount, data.LastError, data.Result)
	return ret, err
}

func (m *defaultSnatchTasksModel) Update(ctx context.Context, data *SnatchTasks) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, snatchTasksRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DomainId, data.Domain, data.Status, data.Priority, data.TargetRegistrar, data.AutoRegister, data.RetryCount, data.LastError, data.Result, data.Id)
	return err
}

func (m *defaultSnatchTasksModel) tableName() string {
	return m.table
}
